// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXgSFaTbBjSyjIKrcBgRD5Cb_bqMTgelc',
    appId: '1:896953338037:web:653904cf4cb44055e996fc',
    messagingSenderId: '896953338037',
    projectId: 'complaint-management-sys-b4c17',
    authDomain: 'complaint-management-sys-b4c17.firebaseapp.com',
    storageBucket: 'complaint-management-sys-b4c17.firebasestorage.app',
    measurementId: 'G-3CTWV1YF21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUoRaATdHxhc2Mb_TiGcIl93s1TMGJfPY',
    appId: '1:896953338037:android:d2950b540a0041d5e996fc',
    messagingSenderId: '896953338037',
    projectId: 'complaint-management-sys-b4c17',
    storageBucket: 'complaint-management-sys-b4c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9tv5L9vUr0O_6bQwhOncg1z8szuEhKjE',
    appId: '1:896953338037:ios:4d4fb5944a09149ae996fc',
    messagingSenderId: '896953338037',
    projectId: 'complaint-management-sys-b4c17',
    storageBucket: 'complaint-management-sys-b4c17.firebasestorage.app',
    iosBundleId: 'com.example.complainManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9tv5L9vUr0O_6bQwhOncg1z8szuEhKjE',
    appId: '1:896953338037:ios:4d4fb5944a09149ae996fc',
    messagingSenderId: '896953338037',
    projectId: 'complaint-management-sys-b4c17',
    storageBucket: 'complaint-management-sys-b4c17.firebasestorage.app',
    iosBundleId: 'com.example.complainManagementSystem',
  );

}